language: cpp
sudo: false
dist: xenial
matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          packages:
            - cmake
            - gcc
            - g++
            - libomp-dev
            - libglu1-mesa-dev
            - libxxf86vm-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libx11-dev
      script:
        - mkdir build
        - gcc --version
        - cd build
        - cmake ..
        - make -j
